0: apple
1: banana
2: beef
3: blueberries
4: bread
5: butter
6: carrot
7: cheese
8: chicken
9: chicken_breast
10: chocolate
11: corn
12: eggs
13: flour
14: goat_cheese
15: green_beans
16: ground_beef
17: ham
18: heavy_cream
19: lime
20: milk
21: mushrooms
22: onion
23: potato
24: shrimp
25: spinach
26: strawberries
27: sugar
28: sweet_potato
29: tomato
